### ISSUE TITLE
Can we use `xmlbuilder` replace `jsdom`?

### ISSUE THREAD

**Issue by yangsibai** [L2jLiga/xd2svg#31]
`jsdom` is  heavy, it seems we just need a xml builder?

I'm not familiar with TypeScript, I tried a while, didn't finish it.  

[xmlbuilder](https://www.npmjs.com/package/xmlbuilder)

**Comment by L2jLiga** [comment]
@yangsibai I've created PR with required changes

**Comment by yangsibai** [comment]
@L2jLiga In my test, it's working well.
